//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaludDCU.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SaludDCU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap asasasas {
            get {
                object obj = ResourceManager.GetObject("asasasas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_gear_setting_5b132e719ea563_8000613215279837296498 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-gear-setting-5b132e719ea563.8000613215279837296498", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_computer_icons_information_clip_art_about_us_5ac1f73a544954_2560494515226611783453 {
            get {
                object obj = ResourceManager.GetObject("kisspng-computer-icons-information-clip-art-about-us-5ac1f73a544954.2560494515226" +
                        "611783453", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_health_professional_community_health_center_medici_localiza_ccedil_atilde_o_5b2ea640aca825_6455165115297838727072 {
            get {
                object obj = ResourceManager.GetObject("kisspng-health-professional-community-health-center-medici-localiza-ccedil-atilde" +
                        "-o-5b2ea640aca825.6455165115297838727072", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_orb_health_health_care_medicine_public_health_5b229f06ce42d2_7686763315289955908449 {
            get {
                object obj = ResourceManager.GetObject("kisspng-orb-health-health-care-medicine-public-health-5b229f06ce42d2.768676331528" +
                        "9955908449", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_orb_health_health_care_medicine_public_health_5b229f06ce42d21 {
            get {
                object obj = ResourceManager.GetObject("kisspng-orb-health-health-care-medicine-public-health-5b229f06ce42d21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_orb_health_health_care_medicine_public_health_5b229f06ce42d22 {
            get {
                object obj = ResourceManager.GetObject("kisspng-orb-health-health-care-medicine-public-health-5b229f06ce42d22", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_patient_computer_icons_hospital_patient_icon_drawing_5ab0a80606ecf5_1533942715215267900284 {
            get {
                object obj = ResourceManager.GetObject("kisspng-patient-computer-icons-hospital-patient-icon-drawing-5ab0a80606ecf5.15339" +
                        "42715215267900284", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_pharmaceutical_drug_computer_icons_tablet_dietary_5af632ca398008_5081823815260842982355 {
            get {
                object obj = ResourceManager.GetObject("kisspng-pharmaceutical-drug-computer-icons-tablet-dietary-5af632ca398008.50818238" +
                        "15260842982355", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_red_x_letter_computer_icons_red_x_5ac2fb75b18a39_2414215415227277977272 {
            get {
                object obj = ResourceManager.GetObject("kisspng-red-x-letter-computer-icons-red-x-5ac2fb75b18a39.2414215415227277977272", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap transparent_document_icon_medical_services_icon_admision_form_5ff90156a743c0_5223766216101543266851 {
            get {
                object obj = ResourceManager.GetObject("transparent-document-icon-medical-services-icon-admision-form-5ff90156a743c0.5223" +
                        "766216101543266851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wdddddddd {
            get {
                object obj = ResourceManager.GetObject("wdddddddd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
